@host = localhost
@port = 8081
@baseUrl = http://{{host}}:{{port}}


### Create Policy
POST {{baseUrl}}/api/policies/create
Content-Type: application/json

{


  "title": "Data Security Policy today moved to docker",
  "description": "Policy for protecting university to docker continerize",
  "createdBy": "tilahun"


}

###

GET {{baseUrl}}/api/policies

###

GET {{baseUrl}}/api/policies/1

###

POST{{baseUrl}}/api/policies/59/submit

###

POST {{baseUrl}}/api/policies/6/reject

###

POST {{baseUrl}}/api/policies/58/approve