@host = localhost
@port = 8081
@baseUrl = http://{{host}}:{{port}}

### Create Policy



POST {{baseUrl}}/api/policies/create
Content-Type: application/json

{
  "title": "Data Security Policy loading fixed docker running",
  "description": "Policy for protecting university after containerization successfully",
  "createdBy": "heven"
}

###

### Get All Policies

GET {{baseUrl}}/api/policies

###

### Get Policy By ID

GET {{baseUrl}}/api/policies/19

###

### Submit Policy

POST {{baseUrl}}/api/policies/18/submit

###

### Reject Policy

POST {{baseUrl}}/api/policies/17/reject

###

### Approve Policy

POST {{baseUrl}}/api/policies/18/approve