@host = localhost
@port = 8081
@baseUrl = http://{{host}}:{{port}}


### Create Policy
POST {{baseUrl}}/api/policies
Content-Type: application/json

{

  "title": "Data Protection Policygggggggggggggggg",
  "description": "Rules for protecting company customer data",
  "createdBy": "admin"

}

###

GET {{baseUrl}}/api/policies

###

GET {{baseUrl}}/api/policies/1

###

POST{{baseUrl}}/api/policies/7/submit

###

POST {{baseUrl}}/api/policies/6/reject

###

POST {{baseUrl}}/api/policies/5/approve